---
- hosts: all
  become: true
  tasks:
  # - name: update distribution
  #   apt:
  #     update_cache: yes
  # - name: install git
  #   apt:
  #     name:
  #       - git
  #       - nodejs
  #       - npm
  #     update_cache: yes
  # - name: file configuration copy
  #   copy: 
  #     src: conf/
  #     dest: / 
  - name: install apache2
    apt:
      name:
        - apache2
      update_cache: yes
  - name: change file permissions
    file:
      path: /var/www/html
      state: directory
      mode: '0755'
  - name: copy fichier
    copy:
      src: index.html
      dest: /var/www/html
  - name: launch service
    ansible.builtin.service:
      name: apache2
      state: started
