---
- hosts: all
  become: true
  tasks:
  - name: installation des packages de docker
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes

# Ajouter la clé gpg pour la sécurité des échanges avec le serveur des packages docker
  - name: ajout de la clé gpg
    apt_key:
      url: https://download.docker.com/linux/debian/gpg

# Ajouter le repos pour chercher les packages de docker 
  - name: ajout de l'adresse de repos pour les packages docker de debian 
    apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable

# Installation des composants docker
  - name: install docker components
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io

# Démarrage du service
  - name: start docker service 
    service:
      name: docker start
      state: started
      enabled: yes

  # - name: copy dossier result
  #   copy:
  #     src: result/
  #     dest: / 
  # - name: copy dossier vote
  #   copy:
  #     src: vote/
  #     dest: / 
  # - name: copy dossier worker
  #   copy:
  #     src: worker/
  #     dest: / 
  # - name: build container image
  #   docker_image:
  #     name: image result
  #     build:
  #       path: result/
  #     state: present 
  # - name: build container image
  #   docker_image:
  #     name: image vote
  #     build:
  #       path: vote/
  #     state: present 
  # - name: build container image
  #   docker_image:
  #     name: image worker
  #     build:
  #       path: worker/
  #     state: present 
