---
- hosts: all
  become: true
  tasks:
  - name: installation docker
    apt:
      name:
        - docker
      update_cache: yes
  - name: copy dossier result
    copy:
      src: result/
      dest: / 
  - name: copy dossier vote
    copy:
      src: vote/
      dest: / 
  - name: copy dossier worker
    copy:
      src: worker/
      dest: / 
  - name: build container image
    docker_image:
      name: image result
      build:
        path: result/
        source: build
      state: present 
  - name: build container image
    docker_image:
      name: image vote
      build:
        path: vote/
        source: build
      state: present 
  - name: build container image
    docker_image:
      name: image worker
      build:
        path: worker/
        source: build
      state: present 
